more Download Queue info
Suwayomi/Tachidesk-WebUI pull request #138
Opened 2022-02-24 19:07 UTC by Robonau

add Imanga type definition to IDownloadChapter

add source name to queue
add manga name to queue

i have some permanently errored downloads and had no information visible other than what chapter it was

before:
![Screenshot_20220224_190602](https://user-images.githubusercontent.com/30987265/155590428-52ff051b-b668-47ea-9cfa-c43cee890c80.png)
after:
![Screenshot_20220224_190624](https://user-images.githubusercontent.com/30987265/155590470-10b59fb8-dcf3-4bef-9b48-e7bbee27a6e9.png)

2022-02-25 18:27 UTC, Robonau commented
now:
![Screenshot_20220225_182803](https://user-images.githubusercontent.com/30987265/155768164-e26a2b2b-724a-4cea-af73-ff1655e0f0e3.png)

2022-02-25 18:28 UTC, Robonau commented
clicking it (anywhere other than the delete icon) takes you to the manga page now too

2022-02-25 18:40 UTC, Robonau commented
![Screenshot_20220225_184150](https://user-images.githubusercontent.com/30987265/155769984-379c18dc-2900-4dad-ad6b-22dba2e384b1.png)

2022-02-25 18:41 UTC, Robonau commented
![Screenshot_20220225_184150](https://user-images.githubusercontent.com/30987265/155770044-61f9ecb1-502b-43e7-b92a-5dea518abf1c.png)

2022-03-03 09:38 UTC, AriaMoradi requested changes

2022-03-03 09:38 UTC, AriaMoradi commented on src/screens/DownloadQueue.tsx
> +/* eslint-disable max-len */
fix this lint error, don't ignore it
Alternatively use styled for instead of sx if its not workable

2022-03-03 21:05 UTC, merged