Added the Download filter and download badge
Suwayomi/Tachidesk-WebUI pull request #62
Opened 2021-11-05 14:38 UTC by abhijeetChawla

Added the download filter to the library and The download badge to the to the mangaCard

2021-11-05 14:43 UTC, ntbm commented on src/components/library/LibraryMangaGrid.tsx
> +
```suggestion

```

2021-11-05 14:49 UTC, ntbm requested changes

2021-11-05 14:49 UTC, ntbm commented on src/components/MangaCard.tsx
> +const BadgeConatiner = styled('div')({
Typo :)
```suggestion
const BadgeContainer = styled('div')({
```

2021-11-05 14:49 UTC, ntbm commented on src/components/MangaCard.tsx
> +                        <BadgeConatiner>
Typo
```suggestion
                        <BadgeContainer>
```

2021-11-05 14:49 UTC, ntbm commented on src/components/MangaCard.tsx
> +                        </BadgeConatiner>
```suggestion
                        </BadgeContainer>
```

2021-11-05 14:49 UTC, ntbm commented on src/components/library/LibraryOptions.tsx
> +        <div style={{ display: 'Flex', flexDirection: 'column' }}>
:)
```suggestion
        <div style={{ display: 'flex', flexDirection: 'column' }}>
```

2021-11-05 14:49 UTC, ntbm commented on src/util/useLibraryOptions.ts
> +    const active = !(unread == undefined) && !(downloaded == undefined);
```suggestion
    const active = !(unread == undefined) || !(downloaded == undefined);
```
It's active when there's a value for the unread filter or the dowloaded filter

2021-11-05 14:51 UTC, AriaMoradi requested changes

2021-11-05 14:51 UTC, AriaMoradi commented on src/components/library/LibraryMangaGrid.tsx
> +// }
No commented code please.

2021-11-05 14:51 UTC, AriaMoradi commented on src/components/library/LibraryMangaGrid.tsx
> +// }
git remembers for you...

2021-11-06 08:01 UTC, abhijeetChawla commented
Changed the Navbar colors in Light mode to make it more legibile
Before
![localhost_3000_library (2)](https://user-images.githubusercontent.com/84376771/140602661-28a4e79b-89f8-4dec-9f4d-43fb7e8cae54.png)
![localhost_3000_library (3)](https://user-images.githubusercontent.com/84376771/140602664-ada3a76a-90ad-402f-bce3-98114d06fa75.png)

After
![localhost_3000_library (4)](https://user-images.githubusercontent.com/84376771/140602671-da842142-fd02-446e-b33f-ce4d3a82b43b.png)
![localhost_3000_library (1)](https://user-images.githubusercontent.com/84376771/140602675-ac19c6c0-49b5-4f24-a28f-d91bbe57fddd.png)

2021-11-06 08:09 UTC, AriaMoradi commented
> Changed the Navbar colors in Light mode to make it more legibile

This commit is not related to the subject of this one, put it in another PR

2021-11-07 10:19 UTC, AriaMoradi approved these changes

2021-11-07 10:29 UTC, merged