Mui 5 migration
Suwayomi/Tachidesk-WebUI pull request #72
Opened 2021-11-10 14:03 UTC by abhijeetChawla

Migrated some components to the mui 5 system

2021-11-10 14:48 UTC, ntbm commented on src/components/ExtensionCard.tsx
> +        paddingBottom: '16px',
That wasn't here before, why did you add it?

2021-11-10 14:48 UTC, ntbm commented on src/components/ExtensionCard.tsx
> +    height: theme.spacing(8),
You're changing the spacing here as well

2021-11-10 14:48 UTC, ntbm commented on src/components/SourceCard.tsx
> +        paddingBottom: '16px',
Wasn't here before

2021-11-10 14:48 UTC, ntbm commented on src/components/SourceCard.tsx
> +    height: theme.spacing(8),
different spacing

2021-11-10 14:48 UTC, ntbm commented on src/screens/settings/About.tsx
> +            <div style={{ display: 'grid', placeItems: 'center', height: '80vh' }}>
Need to check if this is visually correct

2021-11-10 14:48 UTC, ntbm commented on src/screens/Reader.tsx
> +            >
Need to check if this is visually correct

2021-11-10 19:11 UTC, AriaMoradi commented on src/App.tsx
> +                                    marginBottom: { xs: 8, sm: 4 },
keys like `mt`, `ml`, `mb` exist too

2021-11-10 19:12 UTC, AriaMoradi commented on src/components/ExtensionCard.tsx
> +        paddingBottom: '16px',
`pb: 2`

2021-11-10 19:16 UTC, AriaMoradi requested changes

2021-11-10 19:16 UTC, AriaMoradi commented on src/components/ExtensionCard.tsx
> +        <Card style={{ margin: '10px' }}>
use `sx` instead

2021-11-10 19:16 UTC, AriaMoradi commented on src/components/ExtensionCard.tsx
> +                <Box display="flex">
use `sx` for css properties

2021-11-10 19:16 UTC, AriaMoradi commented on src/components/ExtensionCard.tsx
> +                    <Box display="flex" flexDirection="column">
use `sx`

2021-11-10 19:16 UTC, AriaMoradi commented on src/screens/Reader.tsx
> +        <div style={{ width: settings.staticNav ? 'calc(100vw - 300px)' : '100vw' }}>
`sx`

2021-11-10 19:16 UTC, AriaMoradi commented on src/screens/Reader.tsx
> +            }}
`sx`

2021-11-13 09:44 UTC, AriaMoradi requested changes

2021-11-13 09:44 UTC, AriaMoradi commented on src/components/navbar/ReaderNavBar.tsx
> +const useStyles = makeStyles({
There should be a way to eliminate this?

2021-11-13 11:17 UTC, abhijeetChawla commented
So finally done, migration to the MUI 5 system is almost done. Only the manga screen component is left to converted and for that i want to make a seperate pull request

2021-11-13 12:03 UTC, AriaMoradi requested changes

2021-11-13 12:03 UTC, AriaMoradi commented on src/components/navbar/ReaderNavBar.tsx
> +            mainContainer.style.display = 'block';
don't remove the comment

2021-11-13 16:31 UTC, AriaMoradi approved these changes

2021-11-13 16:32 UTC, AriaMoradi commented
@ntbm Can I also have your approval? This is a big PR and I might have missed things in my review.

2021-11-13 17:53 UTC, ntbm commented
I’m out and about right now. Will look at it today
Aria Moradi ***@***.***> schrieb am Sa. 13. Nov. 2021 um
17:32:

> @ntbm <https://github.com/ntbm> Can I also have your approval? This is a
> big PR and I might have missed things in my review.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/Suwayomi/Tachidesk-WebUI/pull/72#issuecomment-968095776>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABG2NSDPKOTDC42BF2HC7FLUL2HJTANCNFSM5HX7GVOQ>
> .
>

2021-11-13 20:05 UTC, ntbm commented
Sources is broken
<img width="1000" alt="Bildschirmfoto 2021-11-13 um 21 04 23" src="https://user-images.githubusercontent.com/5088968/141657555-e215239b-73c0-4c3d-934d-f586759fbeb0.png">
<img width="997" alt="Bildschirmfoto 2021-11-13 um 21 04 15" src="https://user-images.githubusercontent.com/5088968/141657561-91149709-194f-48a7-ac90-55d972977b85.png">

2021-11-13 20:17 UTC, ntbm commented on src/components/SourceCard.tsx
> +                                sx={{ ml: 20 }}
marginLeft: 20 is 20px ml: 20 is theme.spacing(20)

2021-11-13 20:32 UTC, ntbm commented on src/components/SourceCard.tsx
> +                            sx={{ ml: 20 }}
marginLeft: 20 is 20px ml: 20 is theme.spacing(20)

2021-11-13 20:32 UTC, ntbm commented on src/components/SourceCard.tsx
> +                            sx={{ ml: 20 }}
marginLeft: 20 is 20px ml: 20 is theme.spacing(20)

2021-11-13 20:39 UTC, AriaMoradi commented
Also fix the merge conflict

2021-11-14 09:16 UTC, ntbm requested changes

2021-11-14 09:16 UTC, ntbm commented on src/components/ChapterCard.tsx
> +                        >
Remove trailing whitespace
```suggestion
                        >
```

2021-11-14 10:04 UTC, ntbm approved these changes

2021-11-14 10:21 UTC, merged